// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Hooks.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/config/types/helper.hpp>

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
struct Hook;
}
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
using nlohmann::json;

struct Hooks {
std::optional<std::vector<Hook>> createContainer;
std::optional<std::vector<Hook>> createRuntime;
std::optional<std::vector<Hook>> poststart;
std::optional<std::vector<Hook>> poststop;
std::optional<std::vector<Hook>> prestart;
std::optional<std::vector<Hook>> startContainer;
};
}
}
}
}

// clang-format on
