// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Zos.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/config/types/helper.hpp>

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
struct ZosDevice;
}
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
namespace types {
/**
* z/OS platform-specific configurations
*/

using nlohmann::json;

/**
* z/OS platform-specific configurations
*/
struct Zos {
std::optional<std::vector<ZosDevice>> devices;
};
}
}
}
}

// clang-format on
