// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     helper.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <nlohmann/json.hpp>

#include <sstream>

namespace ocppi {
namespace runtime {
namespace list {
namespace types {
using nlohmann::json;

#ifndef NLOHMANN_UNTYPED_ocppi_runtime_list_types_HELPER
#define NLOHMANN_UNTYPED_ocppi_runtime_list_types_HELPER
inline json get_untyped(const json & j, const char * property) {
if (j.find(property) != j.end()) {
return j.at(property).get<json>();
}
return json();
}

inline json get_untyped(const json & j, std::string property) {
return get_untyped(j, property.data());
}
#endif
}
}
}
}

// clang-format on
