// Thish file is generated by /tools/codegen
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Item.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <nlohmann/json.hpp>
#include "ocppi/runtime/list/types/helper.hpp"

namespace ocppi {
namespace runtime {
namespace list {
namespace types {
/**
* crun list schema
*/

using nlohmann::json;

/**
* crun list schema
*/
struct Item {
std::string bundle;
std::string created;
std::string id;
std::string owner;
int64_t pid;
std::string status;
};
}
}
}
}

// clang-format on
