// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Linux.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/config/helper.hpp>

#include <ocppi/runtime/config/IntelRdt.hpp>
#include <ocppi/runtime/config/Personality.hpp>
#include <ocppi/runtime/config/LinuxResources.hpp>
#include <ocppi/runtime/config/Seccomp.hpp>
#include <ocppi/runtime/config/TimeOffsets.hpp>

namespace ocppi {
namespace runtime {
namespace config {
struct LinuxDevice;
struct IdMapping;
struct NamespaceReference;
enum class RootfsPropagation : int;
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
/**
* Linux platform-specific configurations
*/

using nlohmann::json;

/**
* Linux platform-specific configurations
*/
struct Linux {
std::optional<std::string> cgroupsPath;
std::optional<std::vector<LinuxDevice>> devices;
std::optional<std::vector<IdMapping>> gidMappings;
std::optional<IntelRdt> intelRdt;
std::optional<std::vector<std::string>> maskedPaths;
std::optional<std::string> mountLabel;
std::optional<std::vector<NamespaceReference>> namespaces;
std::optional<Personality> personality;
std::optional<std::vector<std::string>> readonlyPaths;
std::optional<LinuxResources> resources;
std::optional<RootfsPropagation> rootfsPropagation;
std::optional<Seccomp> seccomp;
std::optional<std::map<std::string, nlohmann::json>> sysctl;
std::optional<TimeOffsets> timeOffsets;
std::optional<std::vector<IdMapping>> uidMappings;
};
}
}
}

// clang-format on
