// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Scheduler.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/config/helper.hpp>

namespace ocppi {
namespace runtime {
namespace config {
enum class SchedulerFlag : int;
enum class SchedulerPolicy : int;
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
using nlohmann::json;

struct Scheduler {
std::optional<int64_t> deadline;
std::optional<std::vector<SchedulerFlag>> flags;
std::optional<int64_t> nice;
std::optional<int64_t> period;
SchedulerPolicy policy;
std::optional<int64_t> priority;
std::optional<int64_t> runtime;
};
}
}
}

// clang-format on
