// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Solaris.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/config/helper.hpp>

#include <ocppi/runtime/config/CappedCPU.hpp>
#include <ocppi/runtime/config/CappedMemory.hpp>

namespace ocppi {
namespace runtime {
namespace config {
struct Anet;
}
}
}

namespace ocppi {
namespace runtime {
namespace config {
/**
* Solaris platform-specific configurations
*/

using nlohmann::json;

/**
* Solaris platform-specific configurations
*/
struct Solaris {
std::optional<std::vector<Anet>> anet;
std::optional<CappedCPU> cappedCPU;
std::optional<CappedMemory> cappedMemory;
std::optional<std::string> limitpriv;
std::optional<std::string> maxShmMemory;
std::optional<std::string> milestone;
};
}
}
}

// clang-format on
