// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Vm.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/config/helper.hpp>

#include <ocppi/runtime/config/Hypervisor.hpp>
#include <ocppi/runtime/config/Image.hpp>
#include <ocppi/runtime/config/Kernel.hpp>

namespace ocppi {
namespace runtime {
namespace config {
/**
* configuration for virtual-machine-based containers
*/

using nlohmann::json;

/**
* configuration for virtual-machine-based containers
*/
struct Vm {
/**
* hypervisor config used by VM-based containers
*/
std::optional<Hypervisor> hypervisor;
/**
* root image config used by VM-based containers
*/
std::optional<Image> image;
/**
* kernel config used by VM-based containers
*/
Kernel kernel;
};
}
}
}

// clang-format on
