// Thish file is generated by /tools/codegen powered by quicktype.
// DO NOT EDIT IT.

// clang-format off

//  To parse this JSON data, first install
//
//      json.hpp  https://github.com/nlohmann/json
//
//  Then include this file, and then do
//
//     Seccomp.hpp data = nlohmann::json::parse(jsonString);

#pragma once

#include <optional>
#include <nlohmann/json.hpp>
#include <ocppi/runtime/features/helper.hpp>

namespace ocppi {
namespace runtime {
namespace features {
enum class SeccompAction : int;
enum class SeccompArch : int;
enum class SeccompFlag : int;
enum class SeccompOperators : int;
}
}
}

namespace ocppi {
namespace runtime {
namespace features {
using nlohmann::json;

struct Seccomp {
std::optional<std::vector<SeccompAction>> actions;
std::optional<std::vector<SeccompArch>> archs;
std::optional<bool> enabled;
std::optional<std::vector<SeccompFlag>> knownFlags;
std::optional<std::vector<SeccompOperators>> operators;
std::optional<std::vector<SeccompFlag>> supportedFlags;
};
}
}
}

// clang-format on
